version: '3'
services:
  web:
    build: .
    command: gunicorn BrainBites.wsgi:application --bind 0.0.0.0:8000 --log-file - --timeout 190
    ports:
      - "8000:8000"
    restart: always
  worker:
    build: .
    command: celery -A BrainBites worker --loglevel=info
    restart: always
  beat:
    build: .
    command: celery -A BrainBites beat --loglevel=info
    restart: always
