version: '3'
services:
  worker:
    build: .
    command: celery -A BrainBites worker --loglevel=info
    restart: always
  beat:
    build: .
    command: celery -A BrainBites beat --loglevel=info
    restart: always
